### ISSUE TITLE
Why using `use strict`?

### ISSUE THREAD

**Issue by adiTrivsme** [AkshatGKMit/ToDO-List#1]
https://github.com/AkshatGKMit/ToDO-List/blob/00de2e59c232add5666197c03560bb83ef2e4cfb/renders/render.js#L1C1-L1C13

**Comment by AkshatGKMit** [comment]
For using javascript correctly.
if i left a variable undeclared by mistake, so it will throw error.
During the development, in my render table function i forgot to to use const in my tasks variable, so javascript throwed a reference error.
It is helpful is fixing code by strict checking the errors that may not display when using normal javascript code

**Comment by adiTrivsme** [comment]
How come variable declaration errors are not showing with plain JS, without "use strict"?

I am expecting a detailed explanation on Monday updates call
